---
- name: Configure AWS EC2 Image to communicate with Insights via RHC
  hosts: "{{ target_hosts }}"
  
  tasks:
    - name: install SqlServerDsc
      win_psmodule:
        name: SqlServerDsc
        state: present

    - name: copy sql server exe file to host
      win_copy: 
        src: SQL2019-SSEI-Dev.exe
        dest: C:\Windows\Temp\SQL2019-SSEI-Dev.exe

    - name: ensure .net framework is present 
      win_feature:
        name: Net_framework-45-Core
        state: present

#    - name: insall sql server package
